# Generated by Django 5.2.1 on 2025-06-01 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_especialidades', '0001_initial'),
        ('a_pacientes', '0003_alter_pacientes_beneficiario_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_especialidades.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('fuente', models.CharField(max_length=255)),
                ('confiabilidad', models.CharField(blank=True, max_length=225, null=True)),
                ('diagnostico', models.TextField()),
                ('signos_vitales', models.JSONField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_especialidades.especialidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pacientes.pacientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historiales Clinicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_historiales.historialclinico')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('booleano', 'Booleano'), ('fecha', 'Fecha')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveBigIntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='a_historiales.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_historiales.historialclinico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_historiales.pregunta')),
            ],
        ),
    ]
