# Generated by Django 5.2.1 on 2025-06-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_historiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='historial',
        ),
        migrations.AddField(
            model_name='formulario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_historiales.formulario'),
        ),
    ]
