# Generated by Django 5.2.1 on 2025-06-20 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_historiales', '0002_remove_respuesta_historial_formulario_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='historial_clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_historiales.historialclinico'),
        ),
    ]
