# Generated by Django 5.2.1 on 2025-06-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_historiales', '0003_respuesta_historial_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_dato',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('booleano', 'Booleano'), ('fecha', 'Fecha'), ('textarea', 'Texto largo')], max_length=20),
        ),
    ]
