# Generated by Django 5.2.1 on 2025-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_establecimiento', models.CharField(choices=[('hospital', 'Hospital'), ('clinica', ' Clinica'), ('consultorio', 'Consultorio'), ('centroo_salud', 'Centro de Salud')], max_length=20)),
                ('nivel', models.CharField(choices=[('nivel_1', 'Primer Nivel'), ('nivel_2', 'Segundo Nivel'), ('nivel_3', 'Tercer Nivel')], max_length=20)),
            ],
        ),
    ]
