# Generated by Django 5.2.1 on 2025-05-18 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_especialidades', '0001_initial'),
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalEspecialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_especialidades.especialidad')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_sucursales.establecimiento')),
            ],
            options={
                'unique_together': {('sucursal', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='especialidades',
            field=models.ManyToManyField(through='a_sucursales.SucursalEspecialidad', to='a_especialidades.especialidad'),
        ),
    ]
