# Generated by Django 5.2.1 on 2025-06-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_sucursales', '0002_sucursalespecialidad_establecimiento_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo_establecimiento',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinica', 'Clínica'), ('consultorio', 'Consultorio'), ('centro_salud', 'Centro de Salud'), ('laboratorio', 'Laboratorio'), ('farmacia', 'Farmacia')], max_length=20),
        ),
    ]
