# Generated by Django 5.2.1 on 2025-05-18 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField()),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de bitacora',
                'verbose_name_plural': 'Entradas de bitacora',
                'ordering': ['-timestamp'],
            },
        ),
    ]
