# Generated by Django 5.2.1 on 2025-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
