# Generated by Django 5.2.1 on 2025-05-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pacientes', '0002_pacientes_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='beneficiario_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiarios', to='a_pacientes.pacientes'),
        ),
    ]
