# Generated by Django 5.2.1 on 2025-05-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_sucursales', '0002_sucursalespecialidad_establecimiento_especialidades'),
        ('a_usuarios', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_sucursales.establecimiento'),
        ),
    ]
