# Generated by Django 5.2.1 on 2025-06-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_roles', '0001_initial'),
        ('a_usuarios', '0003_alter_usuario_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_roles.rol'),
        ),
    ]
